// Generated by ReScript, PLEASE EDIT WITH CARE


var reg_exp = /^[-!#$%&'*+\/0-9=?A-Z^_a-z`{|}~](\.?[-!#$%&'*+\/0-9=?A-Z^_a-z`{|}~])*@[a-zA-Z0-9](-*\.?[a-zA-Z0-9])*\.[a-zA-Z](-?[a-zA-Z0-9])+$/;

function validate(email) {
  if (email === undefined) {
    return false;
  }
  var emailParts = email.split("@");
  if (emailParts.length !== 2) {
    return false;
  }
  var account = emailParts[0];
  var address = emailParts[1];
  if (account.length <= 64 && address.length <= 255 && address.split(".").every(function (part) {
          return part.length <= 63;
        })) {
    return reg_exp.test(email);
  } else {
    return false;
  }
}

export {
  reg_exp ,
  validate ,
}
/* No side effect */
